apiVersion: v1
kind: Service
metadata:
  name: hotel-service
spec:
  selector:
    app: hotel
  ports:
    - protocol: TCP
      port: 3301
      targetPort: 3301
      nodePort: 30021
  type: NodePort