apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel
  template:
    metadata:
      labels:
        app: hotel
    spec:
      containers:
      - name: hotel
        image: bxr0820/hotel:latest
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "werwerTrip1234"
          - name: MYSQL_DATABASE
            value: "Hotel"
        ports:
        - containerPort: 3306