apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food
  template:
    metadata:
      labels:
        app: food
    spec:
      containers:
      - name: food
        image: qiuer0121/food:latest
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "werwerTrip1234"
          - name: MYSQL_DATABASE
            value: "Food"
        ports:
        - containerPort: 3304