apiVersion: v1
kind: Service
metadata:
  name: train-service
spec:
  selector:
    app: train
  ports:
    - protocol: TCP
      port: 3303
      targetPort: 3303
      nodePort: 30023
  type: NodePort