apiVersion: v1
kind: Service
metadata:
  name: train-service
spec:
  selector:
    app: train
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30003
  type: NodePort