apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: bxr0820/user:latest
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "werwerTrip1234"
          - name: MYSQL_DATABASE
            value: "User"
        ports:
        - containerPort: 3306